apiVersion: apps/v1
kind: Deployment
metadata:
  name: viet-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: viet-app
  template:
    metadata:
      labels:
        app: viet-app
    spec:
      containers:
        - name: viet-app
          image: protemon/my_framework
          ports:
            - containerPort: 80
              name: web
          resources:
            requests:
              memory: "50Mi"
              cpu: "50m"
            limits:
              memory: "75Mi"
              cpu: "75m"
