apiVersion: v1
kind: Service
metadata:
  name: APP_NAME-svc
spec:
  selector:
    app: APP_NAME-app
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      name: goport
  type: NodePort
---